### ISSUE TITLE
Please re-evaluate all model results.

### ISSUE THREAD

**Issue by withwsf** [protagolabs/odyssey-math#5]
Your official prompt directs the model to first give a conclusion, then provide reasons. 

Under this setting, the Chain of Thought (CoT) mechanism does not function effectively. The model generates answers without a process of contemplation, and the subsequent reasoning purely fits the previously generated answer, resulting in significantly skewed results under this setting. 

Moreover, the model can easily refuse to answer, as exemplified by the case in the image from https://github.com/protagolabs/odyssey-math/blob/main/jsonl/gpt-4-0125-preview-solution.jsonl, where numerous refusals to answer do not reflect the model's true capabilities.

![image](https://github.com/protagolabs/odyssey-math/assets/4251313/84ff30ee-153d-4107-be91-8fde74627489)

Your prompt should be revised to the following style, which involves reasoning first and then providing an answer:
```
"content": """
            You are now assuming the role of a math professor. Your task is to assist the user by solving complex mathematical problems in a detailed and step-by-step manner.

            ## Task Requirements:
            1. **Detailed Problem Analysis**: Start by analyzing the given problem. Identify and articulate the key mathematical concepts and techniques needed to solve the problem.
            2. **Step-by-Step Solution**: Decompose the problem into manageable steps. Solve each step sequentially, ensuring logical progression and coherence in your approach.
            3. **Theoretical Justification**: For each step, provide a clear explanation of the mathematical theories or principles applied. Justify your choice of method and demonstrate how it applies to the specific problem at hand.
            4. **Calculation Verification**: After solving each step, verify your calculations. Explain any checks or balances you use to ensure the accuracy of your computations.
            5. **Error Checking and Assumptions**: State any assumptions made during the solution process. Discuss potential errors or alternative methods that could impact the solution.
            6. **Conclusive Summary**: Conclude with a summary of how the steps tie together and confirm the solution's validity.

            ## Expected Output Format:
            Present your final answer and the complete solution process in a JSON format. This should include:
                - A float value or a mathematical algebraic expression for the answer.
                - Detailed reasoning for each step of the solution.

            Your output should be formatted as a JSON object enclosed in Markdown code blocks tagged with 'json'. For example:
            
            
json
            {{ "reasoning": "<detailed solution process>",
                "answer": "<answer>"
            }}

            Ensure that all task requirements are meticulously followed in your response.
        """
```

**Comment by elricwan** [comment]
Now I understand what you are saying. You are saying that since I put answer above the reasoning in the output format, as this:

json
            
            "answer": "<answer>",
            "reasoning": "<detailed solution process>",
                

            
the llm would generate answer first then generate reasoning. That is not what I understand how LLMs works. The output format order would not likely affect how LLM solve the problem. An example is that if we look at the llama output where we use the same prompt, there are clear steps in the reasoning.

https://github.com/protagolabs/odyssey-math/blob/main/jsonl/llama3-70b-solution.jsonl

However, we would love to convert this order and do a test, see if there is any significant difference in performance. Thanks for your advice and that would also be a interesting experiment on how instruction affecting LLMs. I would update you with the newer result

**Comment by withwsf** [comment]
Based on my understanding, the autoregressive paradigm only allows the model to look forward, which means that the model cannot see the CoT process while generating the answer. Therefore, the generated answer does not differ significantly from one without using CoT. I'm glad you're retesting, and I hope to see new results. Good luck!

**Comment by elricwan** [comment]
Hi withwsf, here is the newest result for the model gpt-4-0125-preview. Note the reason I did not use the newest model is that I am afraid the newest model keeps updating. 
```
Overall Accuracy by Level:
  high school competition: 5.41% (8/148)
  high school math: 84.06% (116/138)
  college math: 44.55% (45/101)

Overall Accuracy for the Entire Dataset: 43.67% (169/387)
```
The original result is:

```
Overall Accuracy by Level:
  high school competition: 11.49% (17/148)
  high school math: 74.64% (103/138)
  college math: 41.58% (42/101)

Overall Accuracy for the Entire Dataset: 41.86% (162/387)
```

There is a slightly improvement, may due to the randomness of the model itself. If you check the raw output, the reasoning structure looks similar to the original jsonl.

Here is the prompt I used:
```
You are now assuming the role of a math professor. Your task is to assist the user by solving complex mathematical problems in a detailed and step-by-step manner.

## Task Requirements:

      1...
      2...
      3...
      ......

## Expected Output Format:
            Present your final answer and the complete solution process in a JSON format. This should include:
                - Detailed reasoning for each step of the solution.
                - A `float` value or a mathematical algebraic expression for the answer.
                

            Your output should be formatted as a JSON object enclosed in Markdown code blocks tagged with 'json'. For example:
            
            ```json
            {{
                "reasoning": "<detailed solution process>"
                "answer": "<answer>",
            }}
           ```
```
I attach the raw output, in case you are interested. Feel free to contact me if you have any further questions.

regards
[gpt-4-0125-preview-solution-new.jsonl.zip](https://github.com/user-attachments/files/16145691/gpt-4-0125-preview-solution-new.jsonl.zip)
